### ISSUE TITLE
Front page spacing for featured is incosistent

### ISSUE THREAD

**Issue by mebrett** [omeka/theme-thanksroy#33]
From [this forum post](https://forum.omeka.org/t/correcting-the-spacing-between-featured-exhibit-header-and-exhibit-name/7265/3) - the spacing between headings for featured exhibit and the exhibit is wider than featured item and the item. It looks like it's pulling from Exhibit Record which has a top padding, while Item Record doesn't.

**Comment by zerocrates** [comment]
Yeah, the issue here is that the `.exhibit` style is used to provide some top padding on the exhibits browse page.

There's a little block for specific styling of these "featured" boxes already; simplest solution is to just reset padding to 0 along with border in there. Not sure what's different about the item browse styling but it might just be more targeted.
